package net.aieat.netswissknife.app

import java.io.File
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

class PrivacyAndUiCopyTest {
    @Test
    fun `privacy policy explains Cloudflare synthetic traffic without user data upload`() {
        val policy = repositoryRoot().resolve("PRIVACY_POLICY.md").readText()

        assertTrue(policy.contains("speed.cloudflare.com"))
        assertTrue(policy.contains("synthetic measurement traffic"))
        assertTrue(policy.contains("does not upload your entered hostnames"))
        assertTrue(policy.contains("randomly generated bytes"))
        assertTrue(policy.contains("Cloudflare's privacy policy"))
        assertFalse(policy.contains("No other tool sends data to any external service."))
    }

    @Test
    fun `user-facing Android copy does not contain em dashes`() {
        val root = repositoryRoot()
        val files = buildList {
            add(root.resolve("app/src/main/res/values/strings.xml"))
            addAll(
                root.resolve("app/src/main/kotlin/net/aieat/netswissknife/app/ui")
                    .walkTopDown()
                    .filter { it.isFile && it.extension == "kt" }
                    .toList(),
            )
            addAll(
                listOf(
                    root.resolve("core-network/src/main/kotlin/net/aieat/netswissknife/core/network/dns/DnsServer.kt"),
                    root.resolve("core-network/src/main/kotlin/net/aieat/netswissknife/core/network/dns/DnsRecordType.kt"),
                    root.resolve("core-network/src/main/kotlin/net/aieat/netswissknife/core/network/httprobe/HttpSecurityAnalyzer.kt"),
                    root.resolve("core-network/src/main/kotlin/net/aieat/netswissknife/core/network/wifi/WifiStandard.kt"),
                ),
            )
        }

        val offenders = files.flatMap { file ->
            file.readLines().mapIndexedNotNull { index, line ->
                val trimmed = line.trimStart()
                val isComment = trimmed.startsWith("//") || trimmed.startsWith("/*") || trimmed.startsWith("*")
                if ('—' in line && !isComment) "${file.relativeTo(root)}:${index + 1}" else null
            }
        }

        assertTrue(offenders.isEmpty(), "Em dash found in user-facing UI copy: $offenders")
    }

    private fun repositoryRoot(): File {
        var directory = File(System.getProperty("user.dir") ?: ".").absoluteFile
        while (true) {
            if (directory.resolve("PRIVACY_POLICY.md").isFile) return directory
            directory = directory.parentFile ?: error("Could not find repository root")
        }
    }
}
